// Root layout component for the app, includes global styling and session management
import "./globals.css";
import NextAuthSessionProvider from "../providers/sessionProvider";
import { ReactNode } from "react"; // Import ReactNode for type definition
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define children type as ReactNode
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Amiri:wght@400&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className="font-iransans text-[13px]">
      <ToastContainer position="top-right" autoClose={3000} />

        <NextAuthSessionProvider>
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
